### ISSUE TITLE
Cell instances failing to start in local setups

### ISSUE THREAD

**Issue by MadhukaHarith92** [wso2-cellery/distribution#134]
**Description:**
cell instances are successfully running in gcp and kubeadm setups (both basic and complete). However cell instances are failing to start in local setups (both basic and complete). 

**Affected Product Version:**
latest distribution build.

**OS, DB, other environment details and versions:**    
SDK version : 0.4.0-SNAPSHOT

**Steps to reproduce:**
1. Build a cell image by executing `cellery build` command.
2. Run that cell instance by executing `cellery run` command.

**Related Issues:**
https://github.com/wso2-cellery/sdk/issues/609

**Comment by Mirage20** [comment]
Resolve with https://github.com/wso2-cellery/distribution/pull/135
